### PR TITLE
Port xexxar's pp changes

### PR DESCRIPTION
**Pull request by smoogipoo**
- [x] https://github.com/ppy/osu/pull/15227

### CODE REVIEW

**Comment by peppy** [comment]
Do we have any method to ensure these changes are accurate? I guess after deploy we can confirm by running osu-tools against users?

**Comment by smoogipoo** [comment]
I will provide a spreadsheet in the referenced PR, which you can test via osu-tools.

**Comment by peppy** [comment]
Ah, the spreadsheets are generated using osu-performance aren't they. As long as you're confident that's fine.

**Comment by smoogipoo** [comment]
Tested osu-tools against the spreadsheet in https://github.com/ppy/osu/pull/15227#issuecomment-962640302 and it matches up, so this is good to go.

**Review by peppy — APPROVED** [review]

**Comment by hyyhsuzy** [comment]
Hello, do you know when will the rework updates go live? I was told sometime around 10 UTC, but I didn't find anything related to that myself. 
I'm new to GitHub, sorry if I asked this in the wrong place.

**Comment by smoogipoo** [comment]
It will go live once we're ready, not at a specific time. The changes are finalised, however.

**Comment by hyyhsuzy** [comment]
Alright, thank you!

**Comment by peppy** [comment]
As per usual practice, a timeline will be announced on the osu! site via a news post.

**Pull request merged**
