### PR TITLE
🐋 Add Docker support

### PR DESCRIPTION
**Pull request by ThePooN**

### CODE REVIEW

**Comment by smoogipoo** [comment]
Building image fails with:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20190110ubuntu1.1_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2020a-0ubuntu0.20.04_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-45.49_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-common_2.4.49+dfsg-2ubuntu1.3_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.49+dfsg-2ubuntu1.3_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.68.0-1ubuntu2.2_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.2_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/libmysqlclient21_8.0.21-0ubuntu0.20.04.4_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/libmysqlclient-dev_8.0.21-0ubuntu0.20.04.4_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by ThePooN** [comment]
As per our Discord conversation, this is a broken mirror. Builds fine here.

**Comment by peppy** [comment]
@ThePooN this is still failing fwiw. would be nice to be able to use this if possible.

**Comment by ThePooN** [comment]
with same above error? when i checked after a few hours following smoogi's comment, it worked fine

**Comment by peppy** [comment]
```csharp
 => CACHED [stage-1 2/7] RUN apt-get update                                                                             0.0s
 => CANCELED [builder 3/9] RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libmysqlclient-  5.0s
 => ERROR [stage-1 3/7] RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libmysqlclient21 libcurl4 jq              5.0s
------
 > [stage-1 3/7] RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libmysqlclient21 libcurl4 jq:
#6 0.374 Reading package lists...
#6 1.214 Building dependency tree...
#6 1.368 Reading state information...
#6 1.524 The following additional packages will be installed:
#6 1.524   ca-certificates krb5-locales libasn1-8-heimdal libbrotli1 libgssapi-krb5-2
#6 1.524   libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
#6 1.524   libheimntlm0-heimdal libhx509-5-heimdal libjq1 libk5crypto3 libkeyutils1
#6 1.524   libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
#6 1.525   libnghttp2-14 libonig5 libpsl5 libroken18-heimdal librtmp1 libsasl2-2
#6 1.525   libsasl2-modules libsasl2-modules-db libsqlite3-0 libssh-4 libssl1.1
#6 1.525   libwind0-heimdal mysql-common openssl publicsuffix
#6 1.526 Suggested packages:
#6 1.526   krb5-doc krb5-user libsasl2-modules-gssapi-mit
#6 1.526   | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp
#6 1.526   libsasl2-modules-sql
#6 1.639 The following NEW packages will be installed:
#6 1.639   ca-certificates jq krb5-locales libasn1-8-heimdal libbrotli1 libcurl4
#6 1.639   libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
#6 1.639   libheimntlm0-heimdal libhx509-5-heimdal libjq1 libk5crypto3 libkeyutils1
#6 1.639   libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
#6 1.640   libmysqlclient21 libnghttp2-14 libonig5 libpsl5 libroken18-heimdal librtmp1
#6 1.640   libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssh-4
#6 1.641   libssl1.1 libwind0-heimdal mysql-common openssl publicsuffix
#6 2.093 0 upgraded, 36 newly installed, 0 to remove and 19 not upgraded.
#6 2.093 Need to get 6830 kB of archives.
#6 2.093 After this operation, 24.8 MB of additional disk space will be used.
#6 2.093 Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl1.1 amd64 1.1.1f-1ubuntu2.4 [1319 kB]
#6 3.684 Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 openssl amd64 1.1.1f-1ubuntu2.4 [620 kB]
#6 3.745 Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 ca-certificates all 20210119~20.04.1 [146 kB]
#6 3.755 Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsqlite3-0 amd64 3.31.1-4ubuntu0.2 [549 kB]
#6 3.806 Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 krb5-locales all 1.17-6ubuntu4.1 [11.4 kB]
#6 3.806 Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libkrb5support0 amd64 1.17-6ubuntu4.1 [30.9 kB]
#6 3.893 Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libk5crypto3 amd64 1.17-6ubuntu4.1 [79.9 kB]
#6 3.902 Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 libkeyutils1 amd64 1.6-6ubuntu1 [10.2 kB]
#6 3.903 Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libkrb5-3 amd64 1.17-6ubuntu4.1 [330 kB]
#6 3.932 Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgssapi-krb5-2 amd64 1.17-6ubuntu4.1 [121 kB]
#6 3.943 Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 libpsl5 amd64 0.21.0-1ubuntu1 [51.5 kB]
#6 3.953 Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 publicsuffix all 20200303.0012-1 [111 kB]
#6 3.964 Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 libonig5 amd64 6.9.4-1 [142 kB]
#6 4.015 Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 libjq1 amd64 1.6-1ubuntu0.20.04.1 [121 kB]
#6 4.024 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 jq amd64 1.6-1ubuntu0.20.04.1 [50.2 kB]
#6 4.101 Get:16 http://archive.ubuntu.com/ubuntu focal/main amd64 libroken18-heimdal amd64 7.7.0+dfsg-1ubuntu1 [41.8 kB]
#6 4.110 Get:17 http://archive.ubuntu.com/ubuntu focal/main amd64 libasn1-8-heimdal amd64 7.7.0+dfsg-1ubuntu1 [181 kB]
#6 4.119 Get:18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libbrotli1 amd64 1.0.7-6ubuntu0.1 [267 kB]
#6 4.140 Get:19 http://archive.ubuntu.com/ubuntu focal/main amd64 libheimbase1-heimdal amd64 7.7.0+dfsg-1ubuntu1 [29.7 kB]
#6 4.151 Get:20 http://archive.ubuntu.com/ubuntu focal/main amd64 libhcrypto4-heimdal amd64 7.7.0+dfsg-1ubuntu1 [87.9 kB]
#6 4.155 Get:21 http://archive.ubuntu.com/ubuntu focal/main amd64 libwind0-heimdal amd64 7.7.0+dfsg-1ubuntu1 [48.0 kB]
#6 4.172 Get:22 http://archive.ubuntu.com/ubuntu focal/main amd64 libhx509-5-heimdal amd64 7.7.0+dfsg-1ubuntu1 [107 kB]
#6 4.187 Get:23 http://archive.ubuntu.com/ubuntu focal/main amd64 libkrb5-26-heimdal amd64 7.7.0+dfsg-1ubuntu1 [208 kB]
#6 4.232 Get:24 http://archive.ubuntu.com/ubuntu focal/main amd64 libheimntlm0-heimdal amd64 7.7.0+dfsg-1ubuntu1 [15.1 kB]
#6 4.236 Get:25 http://archive.ubuntu.com/ubuntu focal/main amd64 libgssapi3-heimdal amd64 7.7.0+dfsg-1ubuntu1 [96.1 kB]
#6 4.311 Get:26 http://archive.ubuntu.com/ubuntu focal/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-2 [14.9 kB]
#6 4.328 Get:27 http://archive.ubuntu.com/ubuntu focal/main amd64 libsasl2-2 amd64 2.1.27+dfsg-2 [49.3 kB]
#6 4.342 Get:28 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libldap-common all 2.4.49+dfsg-2ubuntu1.8 [16.6 kB]
#6 4.349 Get:29 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libldap-2.4-2 amd64 2.4.49+dfsg-2ubuntu1.8 [155 kB]
#6 4.363 Get:30 http://archive.ubuntu.com/ubuntu focal/main amd64 libnghttp2-14 amd64 1.40.0-1build1 [78.7 kB]
#6 4.367 Get:31 http://archive.ubuntu.com/ubuntu focal/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2build1 [54.9 kB]
#6 4.385 Get:32 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssh-4 amd64 0.9.3-2ubuntu2.1 [170 kB]
#6 4.405 Ign:33 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.5
#6 4.441 Get:34 http://archive.ubuntu.com/ubuntu focal/main amd64 mysql-common all 5.8+1.0.5ubuntu2 [7496 B]
#6 4.448 Ign:35 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libmysqlclient21 amd64 8.0.25-0ubuntu0.20.04.1
#6 4.519 Get:36 http://archive.ubuntu.com/ubuntu focal/main amd64 libsasl2-modules amd64 2.1.27+dfsg-2 [49.1 kB]
#6 4.789 Err:33 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.5
#6 4.789   404  Not Found [IP: 91.189.88.142 80]
#6 4.971 Err:35 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libmysqlclient21 amd64 8.0.25-0ubuntu0.20.04.1
#6 4.971   404  Not Found [IP: 91.189.88.142 80]
#6 4.983 Fetched 5370 kB in 3s (1616 kB/s)
#6 4.983 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.68.0-1ubuntu2.5_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
#6 4.983 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/libmysqlclient21_8.0.25-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
#6 4.983 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
executor failed running [/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y libmysqlclient21 libcurl4 jq]: exit code: 100

```

**Comment by ThePooN** [comment]
it's building fine here just now. 
your logs show cached layers in use, can you clean it?

**Comment by peppy** [comment]
worked, thanks

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Going to merge this as-is as it looks to be working as expected. Will bring up any issues during actual deployment if they arise.

**Pull request merged**
