### PR TITLE
New FL rebalance values

### PR DESCRIPTION
**Pull request by MBmasher**

### CODE REVIEW

**Comment by peppy** [comment]
@qewc if you have an opinion, please state it in the form of constructive criticism. if you think you can propose something better, please include that proposal.

"it needs to vary more than just this" is not useful at all.

Also this discussion has been ongoing and has already been merged; this is just a minor refactor. Please see #44 for the original discussion.

**Comment by qewc** [comment]
@peppy I have a lot to say about the main changes given, this is just the start of (opinion here) bad changes.

**Comment by MBmasher** [comment]
ok, then why not say it?

**Comment by smoogipoo** [comment]
Sorry for the wait...

Original:
https://original.smgi.me

This PR:
https://mbmasher-fl.smgi.me

Top 100:
https://docs.google.com/spreadsheets/d/1HkgwvBUH1i6qlV6Sc8dLaBZJHGS3FWxhz4yOzwMUwqA/edit?usp=sharing

**Pull request merged**
